server.port=8080
spring.application.name=spring-ai-alibaba

# 字符编码强制为 UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# 阿里云百炼 API Key (sk-...)
spring.ai.dashscope.api-key=sk-ws-H.PMEHYED.6qOk.MEUCIQDKzLfo549jPmNHCUB_Bd1ykl_wT8xpqEwzpZVp5fe_MQIgGUK9d6H6RSlDh1bpTRKFXLhoKzA1YB5z7_jVSjWL6SE

# 通义万象文生图模型配置
spring.ai.dashscope.image.options.model=wanx-v1
